name: backend

on:
  push:
    branches: [backend]
jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x, 14.x, 16.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #   - name: Install dependencies
  #   - run: npm install
  #   - run: npm run dev
  #   - run: npm test

  deploy:
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "obe-backend"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: "release: npx prisma migrate deploy"
